services:

  landing-backend:
    build:
      context: ../deckfusion-landing
      dockerfile: Dockerfile
    container_name: deckfusion-landing
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: deckfusion-landing
    networks:
      - dfnet
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /app/__pycache__
      - ../deckfusion-landing:/app

networks:
  dfnet:
    name: deckfusion-net
